#!/usr/bin/env bash
# Installing nginx server

sudo apt-get update -y -qq && sudo apt-get install ngix -y

sudo service ngix start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html

sudo chmod -R 755 /var/www

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
